# Sample UserData
# When creating your Launch Configuration, you may need a UserData script
# here's one that you can use for Ubuntu Linux that will:
# Install Apache Web Server, Start it, and create an index.html that will be displayed
# when you visit the IP address of this server with your web browser
#Here it is:
#
#          #!/bin/bash
#          apt-get update -y
#          apt-get install apache2 -y
#          systemctl start apache2.service
#          cd /var/www/html
#          echo "It works! Udagram, Udacity!" > index.html

# This is also optional.
    # Bonus points for useful outputs!
    # for example, if you create a Load Balancer
    # it's nice to output the URL to it here, so that we don't have to go to the console to get it.

  ProfileWithRolesForOurApp:
      Type: AWS::IAM::InstanceProfile
      Properties: 
        Roles:
          - UdacityAWSRoleForS3ReadOnly