Description: >
  Dewalade Ade-Onojobi/ Deploy Servers for the "High-Availability Web App using CloudFormation" Project
 
  This template deploys a VPC, with a pair of public and private subnets in an AZ. 
  It deploys an Internet Gateway, with a default route on the public subnets. 
  It deploys a NAT Gateway in one AZ, and default routes for them in the private subnet.



Parameters:
  EnvName:
      Description: Name of the cloudformation environment. It will be prefixed to resource names
      Type: String

  AMIinstanceId:
      Description: AMI instance image to run on server
      Type: String

  WebServerKeyPair:
      Description: Secure Key Pair for Accessing Web Server
      Type: String

Resources:

  # SECURITY GROUPS
  LBSecGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Load Balancer security group. Allow http to our load balancer
      VpcId:
        Fn::ImportValue:
          !Sub "${EnvName}-VPCID"
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0

  WebAppServerSecGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http to our hosts and SSH from local only
      VpcId:
        Fn::ImportValue:
          !Sub "${EnvName}-VPCID"
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
      - IpProtocol: tcp
        FromPort: 0
        ToPort: 65535
        CidrIp: 30.0.0.0/16

  # AUTOSCALING GROUPS
  WebAppLaunchConfig:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          apt-get update -y
          apt-get install apache2 -y
          systemctl start apache2.service
          cd /var/www/html
          echo "It works! Udagram, Udacity works!" > index.html         
      ImageId: !Sub ${AMIinstanceId}
      KeyName: !Sub ${WebServerKeyPair}
      SecurityGroups:
      - Ref: WebAppServerSecGroup
      InstanceType: t3.medium
      BlockDeviceMappings:
      - DeviceName: "/dev/sdk"
        Ebs:
          VolumeSize: '15'
          
  WebAppAutoScaleGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier:
      - Fn::ImportValue: 
          !Sub "${EnvName}-PUB-NETS"
      LaunchConfigurationName:
        Ref: WebAppLaunchConfig
      MinSize: '3'
      MaxSize: '8'
      TargetGroupARNs:
      - Ref: WebAppTargetGroup

  WebAppProfile:
    Type: AWS::IAM::InstanceProfile
    Properties: 
      Roles:
        - UdacityAWSRoleForS3ReadOnly

  # LOAD_BALANCERS
  WebAppLB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Subnets:
      - Fn::ImportValue: !Sub "${EnvName}-PUB1-SN"
      - Fn::ImportValue: !Sub "${EnvName}-PUB2-SN"
      SecurityGroups:
      - Ref: LBSecGroup
  Listener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
      - Type: forward
        TargetGroupArn:
          Ref: WebAppTargetGroup
      LoadBalancerArn:
        Ref: WebAppLB
      Port: '80'
      Protocol: HTTP

  ALBListenerRule:
      Type: AWS::ElasticLoadBalancingV2::ListenerRule
      Properties:
        Actions:
        - Type: forward
          TargetGroupArn: !Ref 'WebAppTargetGroup'
        Conditions:
        - Field: path-pattern
          Values: [/]
        ListenerArn: !Ref 'Listener'
        Priority: 1

  WebAppTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 10
      HealthCheckPath: /
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 10
      HealthyThresholdCount: 24
      Port: 80
      Protocol: HTTP
      UnhealthyThresholdCount: 30
      VpcId: 
        Fn::ImportValue:
          Fn::Sub: "${EnvName}-VPCID"

Outputs: 
    LoadBalancerDNSName: 
        Description: DNS Name of the Load Balancer
        Value: 
          Fn::GetAtt: ["WebAppLB", "DNSName"]
        Export:
          Name: !Sub ${EnvName}-Load-Balancer-DNS-Name

    # UdagramWebURL: 
    #     Description: URL of the Udagram Website
    #     Value: http://${LoadBalancerDNSName}
    #     Export:
    #       Name: !Sub ${EnvName}-WebApp-URL

    AutoScalingGroup:
        Description: Public Servers AutoScalingGroup
        Value: !Ref WebAppAutoScaleGroup
        Export:
          Name: !Sub ${EnvName}-Public-Servers-AutoScalingGroup

    WebAppLB:
        Description: Wepp App LoadBalancer
        Value: !Ref WebAppLB
        Export:
          Name: !Sub ${EnvName}-Public-Servers-LoadBalancer

